
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 03 22:20:54 EDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_PAREN = 32;
  public static final int SEMI = 10;
  public static final int LEFT_CURLY = 2;
  public static final int INT = 12;
  public static final int LESS = 35;
  public static final int MINUS = 22;
  public static final int STATIC = 8;
  public static final int AND = 36;
  public static final int NOT = 30;
  public static final int COMMA = 33;
  public static final int CLASS = 4;
  public static final int RIGHT_CURLY = 3;
  public static final int PLUS = 21;
  public static final int ASSIGN = 18;
  public static final int IF = 14;
  public static final int THIS = 26;
  public static final int ID = 38;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int BOOLEAN = 13;
  public static final int RETURN = 11;
  public static final int VOID_MAIN = 7;
  public static final int TRUE = 24;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int RIGHT_B = 20;
  public static final int UNKNOWN = 34;
  public static final int LEFT_B = 19;
  public static final int TIMES = 23;
  public static final int ELSE = 15;
  public static final int WHILE = 16;
  public static final int PUBLIC = 6;
  public static final int EXTENDS = 9;
  public static final int LEFT_PAREN = 31;
  public static final int STRING = 5;
  public static final int FALSE = 25;
  public static final int PRINT = 17;
  public static final int LENGTH = 28;
  public static final int INTEGER_LITERAL = 37;
}

